#!/bin/bash

if command -v gstat > /dev/null; then
	STAT=gstat
else
	STAT=stat
fi

foobar() {
	echo foobar!
	if [ $# -eq 0 ]; then
		echo "No arguments"
	else
		echo "Arguments: "
		for a in $*; do
			echo "- $a"
		done
	fi

	return 0
}

fileExists() {
	FILENAME=$1
	if [ -f "$FILENAME" ]; then
		return 0
	else
		return 1
	fi
}

fileReadable() {
	FILENAME="$1"
	[ -r "$FILENAME" ]
}

fileUser() {
	FILENAME="$1"
	assertFileExists "$FILENAME"
	$STAT -c %U "$FILENAME"
}

# Returns the permission string of a file, dir, ... (e.g. "-rwxr-x---")
filePerms() {
	FILENAME="$1"
	assertExists "$FILENAME"
	echo $($STAT -c %A "$FILENAME")
}

# Returns 0 (true) if the given file/dir is readable by its owner.
fileReadableByOwner() {
	FILENAME="$1"
	assertFileExists "$FILENAME"
	PERMS=$($STAT -c %A "$FILENAME")
	UREADFLAG=$(echo $PERMS | sed 's/.\(.\).*/\1/')
	[ "$UREADFLAG" = "r" ]
}

# Returns 0 (true) if the given file/dir is readable by its group.
fileReadableByGroup() {
	FILENAME="$1"
	assertFileExists "$FILENAME"
	PERMS=$($STAT -c %A "$FILENAME")
	UREADFLAG=$(echo $PERMS | sed 's/....\(.\).*/\1/')
	[ "$UREADFLAG" = "r" ]
}

# Returns 0 (true) if the given file/dir is readable by other users
fileReadableByOthers() {
	FILENAME="$1"
	assertFileExists "$FILENAME"
	PERMS=$($STAT -c %A "$FILENAME")
	UREADFLAG=$(echo $PERMS | sed 's/.......\(.\).*/\1/')
	[ "$UREADFLAG" = "r" ]
}

# Verifies that a file of the given name exists
assertFileExists() {
	FILENAME="$1"
	if [ ! -f "$FILENAME" ]; then
		echo "Assertion error: file $FILENAME does not exist"
		exit 1
	fi
}

# Verifies that a file or directory of the given name exists
assertExists() {
	FILENAME="$1"
	if [ ! -e "$FILENAME" ]; then
		echo "Assertion error: $FILENAME does not exist"
		exit 1
	fi
}

FILENAMES="holidu bashfun gurt"
for f in $FILENAMES; do
	if fileExists "$f"; then
		echo "$f exists"
	else
		echo "$f doesn't exist"
	fi
	if fileReadable "$f"; then
		echo "$f is readable"
	else
		echo "$f is NOT readable"
	fi
	if fileExists "$f"; then
		echo "- Owner (user):" $(fileUser "$f")
		echo "- Permissions:" $(filePerms "$f")
		if fileReadableByOwner "$f"; then
			echo "- Readable by owner"
		else
			echo "- Not readable by owner"
		fi
		if fileReadableByGroup "$f"; then
			echo "- Readable by group"
		else
			echo "- Not readable by group"
		fi
		if fileReadableByOthers "$f"; then
			echo "- Readable by others"
		else
			echo "- Not readable by others"
		fi
	fi
	echo ""
done

